final try

diff --git a/Jenkinsfile.txt b/Jenkinsfile.txt
--- a/Jenkinsfile.txt
+++ b/Jenkinsfile.txt
@@ -8,7 +8,7 @@ pipeline {
     environment {
         DOCKER_IMAGE = "selimsalmi/spring-app"
         DOCKER_TAG   = "${BUILD_NUMBER}"
-        SONAR_TOKEN  = credentials('sonar-token')
+        SONAR_TOKEN  = "squ_27398fb9a6fd885ad0ddf5f1c43c1840387ea0f2"
     }
 
     stages {
@@ -78,20 +78,16 @@ pipeline {
     }
 
     post {
+        always {
+            sh 'docker logout || true'
+        }
+
         success {
-            archiveArtifacts artifacts: 'target/*.jar',
-                            fingerprint: true,
-                            allowEmptyArchive: true
             echo "✅ Pipeline completed successfully!"
-            echo "📦 Docker Image: ${DOCKER_IMAGE}:${DOCKER_TAG}"
         }
 
         failure {
-            echo "❌ Pipeline failed. Check logs for details."
-        }
-
-        always {
-            sh 'docker logout || true'
+            echo "❌ Pipeline failed. Check logs."
         }
     }
 }
